plugins {
    id 'com.android.application'
}

android {
    namespace 'com.makemyday.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.makemyday.app'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.15.0'
}
